# Update rules and reference lists in Google SecOps based on local rule files.

name: Update Remote Content

on:
  push:
    branches:
      - "main"

  # workflow_dispatch allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  # 'id-token: write' is required to allow GitHub's OIDC provider to create a JSON Web Token for every run
  id-token: write

jobs:
  update-remote-content:
    runs-on: ubuntu-latest

    env:
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      GOOGLE_SECOPS_API_BASE_URL: ${{ vars.GOOGLE_SECOPS_API_BASE_URL }}
      GOOGLE_SECOPS_API_UPLOAD_BASE_URL: ${{ vars.GOOGLE_SECOPS_API_UPLOAD_BASE_URL }}
      GOOGLE_SECOPS_INSTANCE: ${{ vars.GOOGLE_SECOPS_INSTANCE }}
      AUTHORIZATION_SCOPES: ${{ vars.AUTHORIZATION_SCOPES }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GOOGLE_CLOUD_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER}}
          access_token_lifetime: 180s
          export_environment_variables: true
          create_credentials_file: true
          cleanup_credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"  # Caching pip dependencies

      - name: Install Python project dependencies
        run: pip install -r requirements_dev.txt

      # - name: Check Python code formatting with black
      #   run: python -m black google_secops_api content_manager --line-length 120 --check

      - name: Run tests using pytest
        run: pytest -v

      - name: Update reference lists in Google SecOps based on files in main branch
        run: python -m content_manager reference-lists update

      - name: Update data tables in Google SecOps based on files in main branch
        run: python -m content_manager data-tables update

      - name: Update rules in Google SecOps based on files in main branch
        run: python -m content_manager rules update

      # After any changes are made to rules and reference lists in Google SecOps, the latest rules and reference lists are retrieved to update the main branch with the latest data (revision_id, revision_create_time, etc).

      - name: Add files to git staging area
        run: git add rules rule_config.yaml data_tables data_table_config.yaml reference_lists reference_list_config.yaml

      - name: Run git status command
        run: git status  # For debugging

      - name: Commit pending changes
        run: |
          # Check if there are uncommitted changes
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "latest content pulled from google secops api"
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Show last git commit message
        run: git log -1  # For debugging
