networkscanner:
  columns:
  - column_index: 0
    column_type: REGEX
    key_column: true
    mapped_column_path: null
    original_column: scannertools
  create_time: '2025-12-15T02:31:20.543456Z'
  description: 'List of networkscanners '
  resource_name: projects/582443977294/locations/australia-southeast1/instances/600cf364-dd88-4be3-b31d-1e54696ccefd/dataTables/networkscanner
  row_time_to_live: null
  rule_associations_count: null
  rules: null
  update_time: '2026-02-23T02:11:39.182430Z'
  uuid: bd4403f7ae7c4e30a3a26feaf187e60f
