# Chronicle Production Configuration for Detection Rules Repository
# Engineering Officer's Implementation for Captain Picard
# Compatible with Google's official Content Manager structure

# Chronicle API Configuration
chronicle:
  # Regional API endpoints - updated to match Google's official endpoints
  region: "northamerica-northeast2"  # us, europe, asia, northamerica-northeast2
  
  # API URLs (automatically set based on region)
  api_base_url: "https://northamerica-northeast2-chronicle.googleapis.com/v1alpha"
  upload_base_url: "https://northamerica-northeast2-chronicle.googleapis.com/upload/v1alpha"
  
  # Instance configuration - UPDATED with correct organization details
  # Format: projects/{project-id}/locations/{location}/instances/{customer-id}
  instance: "projects/siem-production-2/locations/northamerica-northeast2/instances/87bb0359-c967-420b-952c-3956c9bdc3d3"
  
  # Project details
  project_id: "siem-production-2"
  project_number: "137411790380"
  customer_id: "87bb0359-c967-420b-952c-3956c9bdc3d3"
  
  # Authentication - ABSOLUTE PATH (most reliable for cross-repo access)
  # TODO: Update to new Chronicle SIEM service account once Terraform is applied
  service_account_file: "/Users/erikgrunner/Documents/GitHub/ops/iac/terraform/iam/principals/service-accounts/single-use/live/keys/SECRET_DO_NOT_SHARE.chronicle-siem-manager.json"

  # API behavior
  max_retries: 3
  timeout: 30
  rate_limit_wait: 60

# Local rule management - UPDATED for new directory structure
rules:
  # Directory containing YARAL rule files - RELATIVE TO tools/ops_production/
  directory: "../../rules/custom"
  
  # Rule file configuration
  file_extension: ".yaral"
  encoding: "utf-8"
  
  # Rule deployment defaults
  default_enabled: true
  
  # Validation settings
  validate_before_deploy: true
  skip_validation_on_force: true

# Deployment configuration  
deployment:
  # Batch processing
  batch_size: 10
  concurrent_uploads: 3
  
  # Retry logic
  max_deployment_retries: 3
  retry_delay: 5
  
  # Safety checks
  require_confirmation: true
  backup_before_changes: true

# Rule validation settings
validation:
  # Required rule sections
  required_sections:
    - "meta:"
    - "events:" 
    - "condition:"
  
  # Metadata validation
  required_metadata:
    - "author"
    - "description"
    
  # Syntax checks
  check_balanced_braces: true
  check_yaral_keywords: true
  
  # Chronicle API validation
  use_chronicle_verification: true

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "chronicle_manager.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Console output
  console_output: true
  colored_output: true

# Reporting settings
reporting:
  # Export formats
  export_formats: ["json", "yaml", "csv"]
  
  # Report content
  include_rule_content: false
  include_deployment_status: true
  include_metadata: true
  
  # Output directory
  output_directory: "reports"

# Integration settings
integrations:
  # GitHub integration for CI/CD
  github:
    enabled: false
    repository: ""
    branch: "main"
    
  # Slack notifications
  slack:
    enabled: false
    webhook_url: ""
    
  # Email notifications  
  email:
    enabled: false
    smtp_server: ""
    recipients: []

# Environment-specific overrides
environments:
  development:
    chronicle:
      instance: "projects/siem-dev/locations/northamerica-northeast2/instances/dev-customer-id"
    validation:
      use_chronicle_verification: false
      
  production:
    chronicle:
      instance: "projects/siem-production-2/locations/northamerica-northeast2/instances/87bb0359-c967-420b-952c-3956c9bdc3d3"
    deployment:
      require_confirmation: true
      backup_before_changes: true

# Content Manager compatibility settings
content_manager:
  # Match Google's Content Manager behavior
  compatible_mode: true
  
  # Rule configuration matching their format
  rule_config_file: "rule_config.yaml"
  
  # File naming conventions
  follow_google_naming: true
