data_table_1:
  columns:
  - column_index: 0
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: user_id
  - column_index: 1
    column_type: STRING
    key_column: null
    mapped_column_path: null
    original_column: hostname
  create_time: '2025-05-13T20:22:30.616601Z'
  description: Data table 1
  resource_name: projects/1234567891234/locations/us/instances/3f0ac524-5ae1-4bfd-b86d-53afc953e7e6/dataTables/data_table_1
  row_time_to_live: null
  rule_associations_count: null
  rules: null
  update_time: '2025-05-13T20:22:31.041118Z'
  uuid: d9b6ce36e9874a50945bf8c1cdfc3860
