name: Pull Latest Content

on:
  schedule:
    - cron: "5 23 * * *"
  workflow_dispatch:

permissions:
  contents: write   # id-token removed (not needed for service account)

jobs:
  pull-latest-content:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: tools/content_manager
      LOGGING_LEVEL: ${{ vars.LOGGING_LEVEL }}
      GOOGLE_SECOPS_API_BASE_URL: ${{ vars.GOOGLE_SECOPS_API_BASE_URL }}
      GOOGLE_SECOPS_API_UPLOAD_BASE_URL: ${{ vars.GOOGLE_SECOPS_API_UPLOAD_BASE_URL }}
      GOOGLE_SECOPS_INSTANCE: ${{ vars.GOOGLE_SECOPS_INSTANCE }}
      AUTHORIZATION_SCOPES: ${{ vars.AUTHORIZATION_SCOPES }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Authenticate using Service Account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.credentials_json }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python project dependencies
        run: pip install -r tools/content_manager/requirements_dev.txt

      - name: Run tests using pytest
        run: pytest -v

      - name: Pull latest version of all rules from Google SecOps
        run: python -m content_manager rules get

      - name: Pull latest version of all data tables from Google SecOps
        run: python -m content_manager data-tables get

      - name: Pull latest version of all reference lists from Google SecOps
        run: python -m content_manager reference-lists get

      - name: Add files to git staging area
        run: |
          git add rules
          git add tools/content_manager/rule_config.yaml
          git add tools/content_manager/data_table_config.yaml
          git add tools/content_manager/reference_list_config.yaml
          git add tools/content_manager/data_tables
          git add tools/content_manager/reference_lists

      - name: Run git status command
        run: git status

      - name: Commit pending changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "latest content pulled from google secops api"
            git push origin main
          else
            echo "No changes to commit"
          fi

      - name: Show last git commit message
        run: git log -1
